variables:
  DOCKER_HOST: unix:///var/run/docker.sock # tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: '/certs'
  # DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
  # DOCKER_TLS_VERIFY: 1

image:
  name: docker/compose:1.29.2

services:
  - name: docker:dind
    alias: docker
    command: ['addgroup -g 1000 docker']
    # command: ['--tls=false']

stages:
  - build
  - deploy
  - cleanup

before_script:
  - docker version
  - docker-compose version

build_demo:
  stage: build
  script:
    - echo "DEMO build"
    - docker login -u $AOE_DOCKER_USER -p $AOE_DOCKER_PASS $AOE_DOCKER_REGISTRY
    - docker-compose -f docker-compose.prod.yml build
  only:
    - dev
  tags:
    - demo

deploy_demo:
  stage: deploy
  script:
    - echo "DEMO deploy"
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - dev
  tags:
    - demo

cleanup_demo:
  stage: cleanup
  script:
    - echo "DEMO system clean up"
    - docker system prune -a --volumes -f
  only:
    - dev
  tags:
    - demo

build_prod:
  stage: build
  script:
    - echo "PROD build"
    - docker login -u $AOE_DOCKER_USER -p $AOE_DOCKER_PASS $AOE_DOCKER_REGISTRY
    - docker-compose -f docker-compose.prod.yml build
  only:
    - main
  tags:
    - prod

deploy_prod:
  stage: deploy
  script:
    - echo "PROD deploy"
    - docker-compose -f docker-compose.prod.yml stop
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - main
  tags:
    - prod

cleanup_prod:
  stage: cleanup
  script:
    - echo "PROD system clean up"
    - docker system prune -a --volumes -f
  only:
    - main
  tags:
    - prod
