version: "3.8"
services:
#  aoe-web-backend:
#    build:
#      context: .
#      dockerfile: ./docker/aoe-web-backend/Dockerfile
#    image: aoe-web-backend:latest
#    container_name: aoe-web-backend
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    depends_on:
#      - aoe-postgres
#      - aoe-redis-session
#    environment:
#      - NODE_ENV=development
#    env_file:
#      - ./.env
#    command: sh -c "node dist/server.js"
#    networks:
#      - aoe-local-network

  aoe-postgres:
    build:
      context: .
      dockerfile: ./docker/aoe-postgres/Dockerfile
    image: postgres:12-alpine
    container_name: aoe-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aoe
      - POSTGRES_PASSWORD=aoe_secret
      - POSTGRES_USER=aoe_admin
    volumes:
      - ./docker/aoe-postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/aoe-postgres/aoe-db-dump.sql:/docker-entrypoint-initdb.d/aoe-db-dump.sql
    networks:
      - aoe-local-network

  aoe-redis-session:
    build:
      context: .
      dockerfile: ./docker/aoe-redis-session/Dockerfile
    image: redis-session:6.2.4-alpine
    privileged: true
    command: sh -c "./init.sh"
    container_name: aoe-redis-session
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - aoe-local-network

networks:
  aoe-local-network:
    driver: bridge
