---
- name: Download PostgreSQL repository RPM
  shell: yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  become: true

- name: Install PostgreSQL and requirements
  yum:
    name: [
      python-psycopg2,
      #postgresql,
      postgresql11,
      postgresql11-libs,
      #postgresql-server,
      postgresql11-server,
      postgresql11-contrib
    ]
    state: latest

- name: Make sure configuration directory exists
  file:
    path: /var/lib/pgsql/11/data
    state: directory
    owner: postgres
    group: postgres

- name: Create PostgreSQL database cluster
  command: /usr/pgsql-11/bin/postgresql-11-setup initdb
  #ignore_errors: True

- name: Copy PostgreSQL configuration files
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - {
        src: pg_hba.conf.j2,
        #dest: /var/lib/pgsql/data/pg_hba.conf,
        dest: /var/lib/pgsql/11/data/pg_hba.conf,
        mode: "0600",
        owner: postgres,
        group: postgres
      }
    - { 
        src: postgresql.conf.j2,
        #dest: /var/lib/pgsql/data/postgresql.conf,
        dest: /var/lib/pgsql/11/data/postgresql.conf,
        mode: "0600",
        owner: postgres,
        group: postgres
       }

- name: Create PostgreSQL database cluster 2
  command: systemctl enable postgresql-11
  #ignore_errors: True

- name: Create PostgreSQL database cluster 3
  command: systemctl start postgresql-11
  #ignore_errors: True       
