all:
  children:
    server:
      hosts:
        "127.0.0.1":
          ansible_connection: local
          ansible_ssh_user: vagrant
      vars:
        environment_id: vagrant
        backend_server_path: /opt/aoe-backend
        secrets_file_path: "vars/default-secrets.yml"
