- hosts: server
  become: true
  vars_files:
    - "vars/common.yml"
    - "vars/environments/{{ environment_id }}.yml"
    - "{{ secrets_file_path }}"
  roles:
    # - update
    - os-setup
    - apache
    # - nginx
    - nodejs
    - redis
    - firewall
    - postgres
    - samba
    - services
    - aoe
    - S3
    - clamav
